### PR TITLE
Add crop option

### PR DESCRIPTION
**Pull request by manuelbua**
In the past i thought to have submitted an option for this, but i actually pushed an always-cropping version that wouldn't be good for anyone.

This version is an option where no crop is performed by default, but if the option is specified then:
- `--crop-height`, will crop to the screenshot height
- `--crop-height <num>`, will crop to the specified size

### CODE REVIEW

**Comment by maaaaz** [comment]
Thanks @manuelbua, I can't really figure the use cases for such option, but:
* Is there also a need for a `crop_width` option ?
* Or even better, a global option allowing to specify the [*whole crop rectangle*](https://phantomjs.org/api/webpage/property/clip-rect.html) wouldn't be relevant ? 
  * For instance a `--crop <top,left,width,height>` option: a missing single parameter (or like using a constant "x") would mean "ignore".
  * `--crop x,x,100,200` would mean to take only `width` and `height`

Cheers.

**Comment by manuelbua** [comment]
Yeah, my use case is possibly a bit different but i often don't need the whole page as i just need a glimpse of it, but thumbnails are unusable for sites that renders at 1200x43000.

I also thought about a `--crop` parameter to specify the whole rect as an option but wasn't too sure about it, even in my case i've yet to encounter the need for horizontal cropping or x,y tweaking.

**Comment by maaaaz** [comment]
Ok, I think that I will rather propose a general `--crop` option allowing to specify the whole rectangle.

**Comment by manuelbua** [comment]
Oh it's me me messing with the title, sorry for littering the place 😝 

I just pushed a revision supporting a rectangle definition: also `w` and `h` can be used as to specify the same size as the screen capture.

Only i'm not sure of the way the user is showed an error in case a rectangle is malformed: raising an exception will cause a traceback by default, should we silently fail to the default rect instead?

**Comment by maaaaz** [comment]
Thanks, `--crop` option added in v2.8.


> Oh it's me me messing with the title, sorry for littering the place 😝
> 
> I just pushed a revision supporting a rectangle definition: also `w` and `h` can be used as to specify the same size as the screen capture.
> 
> Only i'm not sure of the way the user is showed an error in case a rectangle is malformed: raising an exception will cause a traceback by default, should we silently fail to the default rect instead?

I expect people using this option to know what they are doing, so there's just a global fail if one component (top, left, width, height) is missing from the splitted value.

**Pull request closed without merging**
